// <auto-generated />
using APDL.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDNetCore.Migrations
{
    [DbContext(typeof(DDDSample1DbContext))]
    [Migration("20251021170633_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("ShippingAgents", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgentRepresentative", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShippingAgentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ShippingAgentId");

                    b.ToTable("ShippingAgentRepresentatives", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.Storage.Facility", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentOccupancyTEU")
                        .HasColumnType("int");

                    b.Property<string>("FacilityType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCapacityTEU")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Facilities", "port");

                    b.HasDiscriminator<string>("FacilityType").HasValue("Facility");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("APDL.API.Domain.VesselTypes.VesselType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxBays")
                        .HasColumnType("int");

                    b.Property<int>("MaxRows")
                        .HasColumnType("int");

                    b.Property<int>("MaxTiers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VesselTypes", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.Storage.Warehouse", b =>
                {
                    b.HasBaseType("APDL.API.Domain.Storage.Facility");

                    b.HasDiscriminator().HasValue("Warehouse");
                });

            modelBuilder.Entity("APDL.API.Domain.Storage.Yard", b =>
                {
                    b.HasBaseType("APDL.API.Domain.Storage.Facility");

                    b.HasDiscriminator().HasValue("Yard");
                });

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgent", b =>
                {
                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Name", "AlternativeName", b1 =>
                        {
                            b1.Property<string>("ShippingAgentId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AlternativeName");

                            b1.HasKey("ShippingAgentId");

                            b1.ToTable("ShippingAgents", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Name", "LegalName", b1 =>
                        {
                            b1.Property<string>("ShippingAgentId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LegalName");

                            b1.HasKey("ShippingAgentId");

                            b1.ToTable("ShippingAgents", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<string>("ShippingAgentId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address");

                            b1.HasKey("ShippingAgentId");

                            b1.ToTable("ShippingAgents", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.TaxNumber", "TaxNumber", b1 =>
                        {
                            b1.Property<string>("ShippingAgentId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TaxNumber");

                            b1.HasKey("ShippingAgentId");

                            b1.ToTable("ShippingAgents", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentId");
                        });

                    b.Navigation("Address");

                    b.Navigation("AlternativeName");

                    b.Navigation("LegalName");

                    b.Navigation("TaxNumber");
                });

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgentRepresentative", b =>
                {
                    b.HasOne("APDL.API.Domain.ShippingAgentAggregate.ShippingAgent", null)
                        .WithMany("Representatives")
                        .HasForeignKey("ShippingAgentId");

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.Email", "Email", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Email");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.CitizenId", "CitizenId", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CitizenId");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Nationality", "Nationality", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Nationality");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Phone");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.Navigation("CitizenId");

                    b.Navigation("Email");

                    b.Navigation("Name");

                    b.Navigation("Nationality");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgent", b =>
                {
                    b.Navigation("Representatives");
                });
#pragma warning restore 612, 618
        }
    }
}
