// <auto-generated />
using System;
using APDL.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDNetCore.Migrations
{
    [DbContext(typeof(DDDSample1DbContext))]
    [Migration("20251119065930_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("APDL.API.Domain.ContainerAggregate.Container", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Containers", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.DockAggregate.StsCrane", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CapacityContainersPerHour")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CapacityContainersPerHour");

                    b.Property<string>("CraneName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("CraneName");

                    b.Property<string>("DockId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredOperators")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RequiredOperators");

                    b.Property<TimeSpan>("SetupTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("SetupTime");

                    b.HasKey("Id");

                    b.HasIndex("DockId");

                    b.ToTable("StsCranes", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.EquipmentAggregate.MobileEquipment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("EquipmentName");

                    b.Property<int>("RequiredOperators")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RequiredOperators");

                    b.Property<TimeSpan>("SetupTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("SetupTime");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentName");

                    b.ToTable("MobileEquipment", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.ManifestAggregate.CargoManifest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLoadingManifest")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsLoadingManifest");

                    b.Property<string>("VesselVisitNotificationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("VesselVisitNotificationId");

                    b.HasKey("Id");

                    b.ToTable("CargoManifests", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.OperatingStaffAggregate.OperatingStaff", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ShortName");

                    b.HasKey("Id");

                    b.ToTable("OperatingStaff", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.QualificationsAggregate.StaffQualification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive");

                    b.Property<string>("QualificationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("QualificationName");

                    b.HasKey("Id");

                    b.ToTable("StaffQualifications", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShippingAgents", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgentRepresentative", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShippingAgentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShippingAgentId");

                    b.ToTable("ShippingAgentRepresentatives", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("APDL.API.Domain.VesselTypes.VesselType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VesselTypes", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.VesselVisitAggregate.VesselVisitNotification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedDockId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaptainName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("CaptainName");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("CargoType");

                    b.Property<int>("CargoVolume")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CargoVolume");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("RejectionReason");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("ReviewedAt");

                    b.Property<string>("ShippingAgentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialHandlingRequirements")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("SpecialHandlingRequirements");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubmittedAt");

                    b.Property<int>("TotalCrewCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalCrewCount");

                    b.Property<string>("VesselId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDockId");

                    b.HasIndex("ShippingAgentId");

                    b.HasIndex("VesselId");

                    b.ToTable("VesselVisitNotifications", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.Vessels.Vessel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselTypeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("Vessels", "port");
                });

            modelBuilder.Entity("Dock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("DockDraft")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DockDraft");

                    b.Property<int>("DockLength")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DockLength");

                    b.Property<string>("DockName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("DockName");

                    b.HasKey("Id");

                    b.HasIndex("DockName")
                        .IsUnique();

                    b.ToTable("Docks", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.ContainerAggregate.Container", b =>
                {
                    b.OwnsOne("APDL.API.Domain.ContainerAggregate.ValueObjects.CargoType", "CargoType", b1 =>
                        {
                            b1.Property<string>("ContainerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("CargoType");

                            b1.HasKey("ContainerId");

                            b1.ToTable("Containers", "port");

                            b1.WithOwner()
                                .HasForeignKey("ContainerId");
                        });

                    b.OwnsOne("APDL.API.Domain.ContainerAggregate.ValueObjects.ContainerDescription", "Description", b1 =>
                        {
                            b1.Property<string>("ContainerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("Description");

                            b1.HasKey("ContainerId");

                            b1.ToTable("Containers", "port");

                            b1.WithOwner()
                                .HasForeignKey("ContainerId");
                        });

                    b.OwnsOne("APDL.API.Domain.ContainerAggregate.ValueObjects.ContainerNumber", "ContainerNumber", b1 =>
                        {
                            b1.Property<string>("ContainerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("ContainerNumber");

                            b1.HasKey("ContainerId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Containers", "port");

                            b1.WithOwner()
                                .HasForeignKey("ContainerId");
                        });

                    b.OwnsOne("APDL.API.Domain.ContainerAggregate.ValueObjects.SpecialRequirements", "SpecialRequirements", b1 =>
                        {
                            b1.Property<string>("ContainerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("SpecialRequirements");

                            b1.HasKey("ContainerId");

                            b1.ToTable("Containers", "port");

                            b1.WithOwner()
                                .HasForeignKey("ContainerId");
                        });

                    b.OwnsOne("APDL.API.Domain.ContainerAggregate.ValueObjects.VesselPosition", "Position", b1 =>
                        {
                            b1.Property<string>("ContainerId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Bay")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Bay");

                            b1.Property<int>("Row")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Row");

                            b1.Property<int>("Tier")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Tier");

                            b1.HasKey("ContainerId");

                            b1.ToTable("Containers", "port");

                            b1.WithOwner()
                                .HasForeignKey("ContainerId");
                        });

                    b.Navigation("CargoType");

                    b.Navigation("ContainerNumber");

                    b.Navigation("Description");

                    b.Navigation("Position");

                    b.Navigation("SpecialRequirements");
                });

            modelBuilder.Entity("APDL.API.Domain.DockAggregate.StsCrane", b =>
                {
                    b.HasOne("Dock", null)
                        .WithMany("STSCranes")
                        .HasForeignKey("DockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("APDL.API.Domain.Shared.ValueObjects.OperationalWindow", "OperationalWindow", b1 =>
                        {
                            b1.Property<string>("StsCraneId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("EndDay")
                                .HasColumnType("INTEGER")
                                .HasColumnName("OperationalEndDay");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("OperationalEndTime");

                            b1.Property<bool>("Is24x7")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Is24x7");

                            b1.Property<int>("StartDay")
                                .HasColumnType("INTEGER")
                                .HasColumnName("OperationalStartDay");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("OperationalStartTime");

                            b1.HasKey("StsCraneId");

                            b1.ToTable("StsCranes", "port");

                            b1.WithOwner()
                                .HasForeignKey("StsCraneId");
                        });

                    b.OwnsOne("APDL.API.Domain.Shared.ValueObjects.QualificationType", "RequiredQualification", b1 =>
                        {
                            b1.Property<string>("StsCraneId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("RequiredQualification");

                            b1.HasKey("StsCraneId");

                            b1.ToTable("StsCranes", "port");

                            b1.WithOwner()
                                .HasForeignKey("StsCraneId");
                        });

                    b.OwnsOne("APDL.API.Domain.Shared.ValueObjects.ResourceStatus", "Status", b1 =>
                        {
                            b1.Property<string>("StsCraneId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Status");

                            b1.HasKey("StsCraneId");

                            b1.ToTable("StsCranes", "port");

                            b1.WithOwner()
                                .HasForeignKey("StsCraneId");
                        });

                    b.Navigation("OperationalWindow");

                    b.Navigation("RequiredQualification");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("APDL.API.Domain.EquipmentAggregate.MobileEquipment", b =>
                {
                    b.OwnsOne("APDL.API.Domain.Shared.ValueObjects.OperationalWindow", "OperationalWindow", b1 =>
                        {
                            b1.Property<string>("MobileEquipmentId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("EndDay")
                                .HasColumnType("INTEGER")
                                .HasColumnName("OperationalEndDay");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("OperationalEndTime");

                            b1.Property<bool>("Is24x7")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Is24x7");

                            b1.Property<int>("StartDay")
                                .HasColumnType("INTEGER")
                                .HasColumnName("OperationalStartDay");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("OperationalStartTime");

                            b1.HasKey("MobileEquipmentId");

                            b1.ToTable("MobileEquipment", "port");

                            b1.WithOwner()
                                .HasForeignKey("MobileEquipmentId");
                        });

                    b.OwnsOne("APDL.API.Domain.Shared.ValueObjects.QualificationType", "RequiredQualification", b1 =>
                        {
                            b1.Property<string>("MobileEquipmentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("RequiredQualification");

                            b1.HasKey("MobileEquipmentId");

                            b1.ToTable("MobileEquipment", "port");

                            b1.WithOwner()
                                .HasForeignKey("MobileEquipmentId");
                        });

                    b.OwnsOne("APDL.API.Domain.Shared.ValueObjects.ResourceStatus", "Status", b1 =>
                        {
                            b1.Property<string>("MobileEquipmentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Status");

                            b1.HasKey("MobileEquipmentId");

                            b1.ToTable("MobileEquipment", "port");

                            b1.WithOwner()
                                .HasForeignKey("MobileEquipmentId");
                        });

                    b.OwnsOne("APDL.API.Domain.MobileEquipmentAggregate.ValueObjects.EquipmentCapacity", "Capacity", b1 =>
                        {
                            b1.Property<string>("MobileEquipmentId")
                                .HasColumnType("TEXT");

                            b1.Property<double?>("AverageSpeedPerHour")
                                .HasColumnType("REAL")
                                .HasColumnName("AverageSpeedPerHour");

                            b1.Property<int?>("ContainersPerHour")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ContainersPerHour");

                            b1.Property<int?>("ContainersPerTrip")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ContainersPerTrip");

                            b1.HasKey("MobileEquipmentId");

                            b1.ToTable("MobileEquipment", "port");

                            b1.WithOwner()
                                .HasForeignKey("MobileEquipmentId");
                        });

                    b.OwnsOne("APDL.API.Domain.MobileEquipmentAggregate.ValueObjects.EquipmentType", "EquipmentType", b1 =>
                        {
                            b1.Property<string>("MobileEquipmentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("EquipmentType");

                            b1.HasKey("MobileEquipmentId");

                            b1.ToTable("MobileEquipment", "port");

                            b1.WithOwner()
                                .HasForeignKey("MobileEquipmentId");
                        });

                    b.Navigation("Capacity");

                    b.Navigation("EquipmentType");

                    b.Navigation("OperationalWindow");

                    b.Navigation("RequiredQualification");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("APDL.API.Domain.ManifestAggregate.CargoManifest", b =>
                {
                    b.OwnsOne("APDL.API.Domain.CargoManifestAggregate.ValueObjects.CargoVolume", "CargoVolume", b1 =>
                        {
                            b1.Property<string>("CargoManifestId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("CargoVolume");

                            b1.HasKey("CargoManifestId");

                            b1.ToTable("CargoManifests", "port");

                            b1.WithOwner()
                                .HasForeignKey("CargoManifestId");
                        });

                    b.OwnsMany("APDL.API.Domain.ContainerAggregate.ContainerId", "_containerIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CargoManifestId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ContainerId");

                            b1.HasKey("Id");

                            b1.HasIndex("CargoManifestId");

                            b1.ToTable("CargoManifestContainers", "port");

                            b1.WithOwner()
                                .HasForeignKey("CargoManifestId");
                        });

                    b.Navigation("CargoVolume");

                    b.Navigation("_containerIds");
                });

            modelBuilder.Entity("APDL.API.Domain.OperatingStaffAggregate.OperatingStaff", b =>
                {
                    b.OwnsOne("APDL.API.Domain.Shared.ValueObjects.OperationalWindow", "OperationalWindow", b1 =>
                        {
                            b1.Property<string>("OperatingStaffId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("EndDay")
                                .HasColumnType("INTEGER")
                                .HasColumnName("OperationalEndDay");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("OperationalEndTime");

                            b1.Property<bool>("Is24x7")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Is24x7");

                            b1.Property<int>("StartDay")
                                .HasColumnType("INTEGER")
                                .HasColumnName("OperationalStartDay");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("TEXT")
                                .HasColumnName("OperationalStartTime");

                            b1.HasKey("OperatingStaffId");

                            b1.ToTable("OperatingStaff", "port");

                            b1.WithOwner()
                                .HasForeignKey("OperatingStaffId");
                        });

                    b.OwnsMany("APDL.API.Domain.Shared.ValueObjects.QualificationType", "Qualifications", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("OperatingStaffId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("QualificationType");

                            b1.HasKey("Id");

                            b1.HasIndex("OperatingStaffId");

                            b1.ToTable("OperatingStaffQualifications", "port");

                            b1.WithOwner()
                                .HasForeignKey("OperatingStaffId");
                        });

                    b.OwnsOne("APDL.API.Domain.OperatingStaffAggregate.ValueObjects.MecanographicNumber", "MecanographicNumber", b1 =>
                        {
                            b1.Property<string>("OperatingStaffId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("MecanographicNumber");

                            b1.HasKey("OperatingStaffId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("OperatingStaff", "port");

                            b1.WithOwner()
                                .HasForeignKey("OperatingStaffId");
                        });

                    b.OwnsOne("APDL.API.Domain.OperatingStaffAggregate.ValueObjects.StaffStatus", "Status", b1 =>
                        {
                            b1.Property<string>("OperatingStaffId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Status");

                            b1.HasKey("OperatingStaffId");

                            b1.ToTable("OperatingStaff", "port");

                            b1.WithOwner()
                                .HasForeignKey("OperatingStaffId");
                        });

                    b.Navigation("MecanographicNumber");

                    b.Navigation("OperationalWindow");

                    b.Navigation("Qualifications");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("APDL.API.Domain.QualificationsAggregate.StaffQualification", b =>
                {
                    b.OwnsOne("APDL.API.Domain.Shared.ValueObjects.QualificationType", "QualificationType", b1 =>
                        {
                            b1.Property<string>("StaffQualificationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("QualificationType");

                            b1.HasKey("StaffQualificationId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("StaffQualifications", "port");

                            b1.WithOwner()
                                .HasForeignKey("StaffQualificationId");
                        });

                    b.Navigation("QualificationType");
                });

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgent", b =>
                {
                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Name", "AlternativeName", b1 =>
                        {
                            b1.Property<string>("ShippingAgentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("AlternativeName");

                            b1.HasKey("ShippingAgentId");

                            b1.ToTable("ShippingAgents", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Name", "LegalName", b1 =>
                        {
                            b1.Property<string>("ShippingAgentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("LegalName");

                            b1.HasKey("ShippingAgentId");

                            b1.ToTable("ShippingAgents", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<string>("ShippingAgentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Address");

                            b1.HasKey("ShippingAgentId");

                            b1.ToTable("ShippingAgents", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.TaxNumber", "TaxNumber", b1 =>
                        {
                            b1.Property<string>("ShippingAgentId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("TaxNumber");

                            b1.HasKey("ShippingAgentId");

                            b1.ToTable("ShippingAgents", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentId");
                        });

                    b.Navigation("Address");

                    b.Navigation("AlternativeName");

                    b.Navigation("LegalName");

                    b.Navigation("TaxNumber");
                });

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgentRepresentative", b =>
                {
                    b.HasOne("APDL.API.Domain.ShippingAgentAggregate.ShippingAgent", null)
                        .WithMany("Representatives")
                        .HasForeignKey("ShippingAgentId");

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.Email", "Email", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.CitizenId", "CitizenId", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("CitizenId");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Nationality", "Nationality", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Nationality");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Phone");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.Navigation("CitizenId");

                    b.Navigation("Email");

                    b.Navigation("Name");

                    b.Navigation("Nationality");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("APDL.API.Domain.VesselTypes.VesselType", b =>
                {
                    b.OwnsOne("APDL.API.Domain.VesselTypes.ValueObjects.Capacity", "Capacity", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Capacity");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("APDL.API.Domain.VesselTypes.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Description");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("APDL.API.Domain.VesselTypes.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("APDL.API.Domain.VesselTypes.ValueObjects.Dimension", "MaxBays", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxBays");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("APDL.API.Domain.VesselTypes.ValueObjects.Dimension", "MaxRows", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxRows");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("APDL.API.Domain.VesselTypes.ValueObjects.Dimension", "MaxTiers", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxTiers");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.Navigation("Capacity");

                    b.Navigation("Description");

                    b.Navigation("MaxBays");

                    b.Navigation("MaxRows");

                    b.Navigation("MaxTiers");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("APDL.API.Domain.VesselVisitAggregate.VesselVisitNotification", b =>
                {
                    b.OwnsMany("APDL.API.Domain.ManifestAggregate.CargoManifestId", "_cargoManifestIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("CargoManifestId");

                            b1.Property<string>("VesselVisitNotificationId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitCargoManifests", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.OwnsOne("APDL.API.Domain.NotificationAggregate.ValueObjects.ExpectedArrival", "ExpectedArrival", b1 =>
                        {
                            b1.Property<string>("VesselVisitNotificationId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("ExpectedArrival");

                            b1.HasKey("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitNotifications", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.OwnsOne("APDL.API.Domain.NotificationAggregate.ValueObjects.ExpectedDeparture", "ExpectedDeparture", b1 =>
                        {
                            b1.Property<string>("VesselVisitNotificationId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("ExpectedDeparture");

                            b1.HasKey("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitNotifications", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.OwnsOne("APDL.API.Domain.NotificationAggregate.ValueObjects.NotificationStatus", "Status", b1 =>
                        {
                            b1.Property<string>("VesselVisitNotificationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("Status");

                            b1.HasKey("VesselVisitNotificationId");

                            b1.HasIndex("Value");

                            b1.ToTable("VesselVisitNotifications", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.OwnsMany("APDL.API.Domain.NotificationAggregate.ValueObjects.SafetyOfficer", "_safetyCrewOfficers", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("OfficerName");

                            b1.Property<string>("VesselVisitNotificationId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitSafetyOfficers", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.Navigation("ExpectedArrival");

                    b.Navigation("ExpectedDeparture");

                    b.Navigation("Status");

                    b.Navigation("_cargoManifestIds");

                    b.Navigation("_safetyCrewOfficers");
                });

            modelBuilder.Entity("APDL.API.Domain.Vessels.Vessel", b =>
                {
                    b.HasOne("APDL.API.Domain.VesselTypes.VesselType", "VesselType")
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("APDL.API.Domain.Vessels.ValueObjects.ImoNumber", "ImoNumber", b1 =>
                        {
                            b1.Property<Guid>("VesselId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("TEXT")
                                .HasColumnName("ImoNumber");

                            b1.HasKey("VesselId");

                            b1.ToTable("Vessels", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselId");
                        });

                    b.OwnsOne("APDL.API.Domain.Vessels.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("VesselId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("Name");

                            b1.HasKey("VesselId");

                            b1.ToTable("Vessels", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselId");
                        });

                    b.OwnsOne("APDL.API.Domain.Vessels.ValueObjects.Operator", "Operator", b1 =>
                        {
                            b1.Property<Guid>("VesselId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("Operator");

                            b1.HasKey("VesselId");

                            b1.ToTable("Vessels", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselId");
                        });

                    b.Navigation("ImoNumber");

                    b.Navigation("Name");

                    b.Navigation("Operator");

                    b.Navigation("VesselType");
                });

            modelBuilder.Entity("Dock", b =>
                {
                    b.OwnsOne("APDL.API.Domain.DockAggregate.ValueObjects.UpcomingMaintenances", "UpcomingMaintenances", b1 =>
                        {
                            b1.Property<string>("DockId")
                                .HasColumnType("TEXT");

                            b1.HasKey("DockId");

                            b1.ToTable("Docks", "port");

                            b1.WithOwner()
                                .HasForeignKey("DockId");

                            b1.OwnsMany("APDL.API.Domain.DockAggregate.ValueObjects.MaintenanceSchedule", "Schedules", b2 =>
                                {
                                    b2.Property<string>("UpcomingMaintenancesDockId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Description");

                                    b2.Property<DateTime>("EstimatedEndDate")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("EstimatedEndDate");

                                    b2.Property<DateTime>("ScheduledDate")
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ScheduledDate");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Type");

                                    b2.HasKey("UpcomingMaintenancesDockId", "Id");

                                    b2.ToTable("DockMaintenanceSchedules", "port");

                                    b2.WithOwner()
                                        .HasForeignKey("UpcomingMaintenancesDockId");
                                });

                            b1.Navigation("Schedules");
                        });

                    b.Navigation("UpcomingMaintenances");
                });

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgent", b =>
                {
                    b.Navigation("Representatives");
                });

            modelBuilder.Entity("Dock", b =>
                {
                    b.Navigation("STSCranes");
                });
#pragma warning restore 612, 618
        }
    }
}
