// <auto-generated />
using System;
using APDL.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDNetCore.Migrations
{
    [DbContext(typeof(DDDSample1DbContext))]
    [Migration("20251026191348_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APDL.API.Domain.ContainerAggregate.Container", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Containers", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.ManifestAggregate.CargoManifest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsLoadingManifest")
                        .HasColumnType("bit")
                        .HasColumnName("IsLoadingManifest");

                    b.Property<string>("VesselVisitNotificationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VesselVisitNotificationId");

                    b.HasKey("Id");

                    b.ToTable("CargoManifests", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("ShippingAgents", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgentRepresentative", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ShippingAgentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ShippingAgentId");

                    b.ToTable("ShippingAgentRepresentatives", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.Storage.Facility", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentOccupancyTEU")
                        .HasColumnType("int");

                    b.Property<string>("FacilityType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Facilities", "port");

                    b.HasDiscriminator<string>("FacilityType").HasValue("Facility");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("APDL.API.Domain.VesselTypes.VesselType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("VesselTypes", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.VesselVisitAggregate.VesselVisitNotification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("VesselVisitNotifications", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.Vessels.Vessel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VesselTypeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("Vessels", "port");
                });

            modelBuilder.Entity("APDL.API.Domain.Storage.Warehouse", b =>
                {
                    b.HasBaseType("APDL.API.Domain.Storage.Facility");

                    b.HasDiscriminator().HasValue("Warehouse");
                });

            modelBuilder.Entity("APDL.API.Domain.Storage.Yard", b =>
                {
                    b.HasBaseType("APDL.API.Domain.Storage.Facility");

                    b.HasDiscriminator().HasValue("Yard");
                });

            modelBuilder.Entity("APDL.API.Domain.ContainerAggregate.Container", b =>
                {
                    b.OwnsOne("APDL.API.Domain.ContainerAggregate.ValueObjects.CargoType", "CargoType", b1 =>
                        {
                            b1.Property<string>("ContainerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("CargoType");

                            b1.HasKey("ContainerId");

                            b1.ToTable("Containers", "port");

                            b1.WithOwner()
                                .HasForeignKey("ContainerId");
                        });

                    b.OwnsOne("APDL.API.Domain.ContainerAggregate.ValueObjects.ContainerDescription", "Description", b1 =>
                        {
                            b1.Property<string>("ContainerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("Description");

                            b1.HasKey("ContainerId");

                            b1.ToTable("Containers", "port");

                            b1.WithOwner()
                                .HasForeignKey("ContainerId");
                        });

                    b.OwnsOne("APDL.API.Domain.ContainerAggregate.ValueObjects.ContainerNumber", "ContainerNumber", b1 =>
                        {
                            b1.Property<string>("ContainerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("ContainerNumber");

                            b1.HasKey("ContainerId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasFilter("[ContainerNumber] IS NOT NULL");

                            b1.ToTable("Containers", "port");

                            b1.WithOwner()
                                .HasForeignKey("ContainerId");
                        });

                    b.OwnsOne("APDL.API.Domain.ContainerAggregate.ValueObjects.SpecialRequirements", "SpecialRequirements", b1 =>
                        {
                            b1.Property<string>("ContainerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("SpecialRequirements");

                            b1.HasKey("ContainerId");

                            b1.ToTable("Containers", "port");

                            b1.WithOwner()
                                .HasForeignKey("ContainerId");
                        });

                    b.OwnsOne("APDL.API.Domain.ContainerAggregate.ValueObjects.VesselPosition", "Position", b1 =>
                        {
                            b1.Property<string>("ContainerId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Bay")
                                .HasColumnType("int")
                                .HasColumnName("Bay");

                            b1.Property<int>("Row")
                                .HasColumnType("int")
                                .HasColumnName("Row");

                            b1.Property<int>("Tier")
                                .HasColumnType("int")
                                .HasColumnName("Tier");

                            b1.HasKey("ContainerId");

                            b1.ToTable("Containers", "port");

                            b1.WithOwner()
                                .HasForeignKey("ContainerId");
                        });

                    b.Navigation("CargoType");

                    b.Navigation("ContainerNumber");

                    b.Navigation("Description");

                    b.Navigation("Position");

                    b.Navigation("SpecialRequirements");
                });

            modelBuilder.Entity("APDL.API.Domain.ManifestAggregate.CargoManifest", b =>
                {
                    b.OwnsOne("APDL.API.Domain.CargoManifestAggregate.ValueObjects.CargoVolume", "CargoVolume", b1 =>
                        {
                            b1.Property<string>("CargoManifestId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("CargoVolume");

                            b1.HasKey("CargoManifestId");

                            b1.ToTable("CargoManifests", "port");

                            b1.WithOwner()
                                .HasForeignKey("CargoManifestId");
                        });

                    b.OwnsMany("APDL.API.Domain.ContainerAggregate.ContainerId", "_containerIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("CargoManifestId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ContainerId");

                            b1.HasKey("Id");

                            b1.HasIndex("CargoManifestId");

                            b1.ToTable("CargoManifestContainers", "port");

                            b1.WithOwner()
                                .HasForeignKey("CargoManifestId");
                        });

                    b.Navigation("CargoVolume");

                    b.Navigation("_containerIds");
                });

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgent", b =>
                {
                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Name", "AlternativeName", b1 =>
                        {
                            b1.Property<string>("ShippingAgentId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("AlternativeName");

                            b1.HasKey("ShippingAgentId");

                            b1.ToTable("ShippingAgents", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Name", "LegalName", b1 =>
                        {
                            b1.Property<string>("ShippingAgentId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("LegalName");

                            b1.HasKey("ShippingAgentId");

                            b1.ToTable("ShippingAgents", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<string>("ShippingAgentId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address");

                            b1.HasKey("ShippingAgentId");

                            b1.ToTable("ShippingAgents", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.TaxNumber", "TaxNumber", b1 =>
                        {
                            b1.Property<string>("ShippingAgentId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("TaxNumber");

                            b1.HasKey("ShippingAgentId");

                            b1.ToTable("ShippingAgents", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentId");
                        });

                    b.Navigation("Address");

                    b.Navigation("AlternativeName");

                    b.Navigation("LegalName");

                    b.Navigation("TaxNumber");
                });

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgentRepresentative", b =>
                {
                    b.HasOne("APDL.API.Domain.ShippingAgentAggregate.ShippingAgent", null)
                        .WithMany("Representatives")
                        .HasForeignKey("ShippingAgentId");

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.Email", "Email", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Email");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.CitizenId", "CitizenId", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CitizenId");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Nationality", "Nationality", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Nationality");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.OwnsOne("APDL.API.Domain.ShippingAgentAggregate.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<string>("ShippingAgentRepresentativeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Phone");

                            b1.HasKey("ShippingAgentRepresentativeId");

                            b1.ToTable("ShippingAgentRepresentatives", "port");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentRepresentativeId");
                        });

                    b.Navigation("CitizenId");

                    b.Navigation("Email");

                    b.Navigation("Name");

                    b.Navigation("Nationality");

                    b.Navigation("Phone");
                });

            modelBuilder.Entity("APDL.API.Domain.Storage.Facility", b =>
                {
                    b.OwnsMany("APDL.API.Domain.Storage.FacilityDockAssignment", "DockAssignments", b1 =>
                        {
                            b1.Property<string>("FacilityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("DebugColumn1")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("DockId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("DockId");

                            b1.HasKey("FacilityId", "Id");

                            b1.ToTable("FacilityDockAssignments", "port");

                            b1.WithOwner()
                                .HasForeignKey("FacilityId");

                            b1.OwnsOne("APDL.API.Domain.Storage.ValueObjects.Distance", "DistanceToDock", b2 =>
                                {
                                    b2.Property<string>("FacilityDockAssignmentFacilityId")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<int>("FacilityDockAssignmentId")
                                        .HasColumnType("int");

                                    b2.Property<double>("Meters")
                                        .HasColumnType("float")
                                        .HasColumnName("DistanceToDock");

                                    b2.HasKey("FacilityDockAssignmentFacilityId", "FacilityDockAssignmentId");

                                    b2.ToTable("FacilityDockAssignments", "port");

                                    b2.WithOwner()
                                        .HasForeignKey("FacilityDockAssignmentFacilityId", "FacilityDockAssignmentId");
                                });

                            b1.Navigation("DistanceToDock");
                        });

                    b.OwnsOne("APDL.API.Domain.Storage.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<string>("FacilityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Location");

                            b1.HasKey("FacilityId");

                            b1.ToTable("Facilities", "port");

                            b1.WithOwner()
                                .HasForeignKey("FacilityId");
                        });

                    b.OwnsOne("APDL.API.Domain.Storage.ValueObjects.TEUCapacity", "MaxCapacityTEU", b1 =>
                        {
                            b1.Property<string>("FacilityId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("MaxCapacityTEU");

                            b1.HasKey("FacilityId");

                            b1.ToTable("Facilities", "port");

                            b1.WithOwner()
                                .HasForeignKey("FacilityId");
                        });

                    b.Navigation("DockAssignments");

                    b.Navigation("Location");

                    b.Navigation("MaxCapacityTEU");
                });

            modelBuilder.Entity("APDL.API.Domain.VesselTypes.VesselType", b =>
                {
                    b.OwnsOne("APDL.API.Domain.VesselTypes.ValueObjects.Capacity", "Capacity", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Capacity");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("APDL.API.Domain.VesselTypes.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("APDL.API.Domain.VesselTypes.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("APDL.API.Domain.VesselTypes.ValueObjects.Dimension", "MaxBays", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("MaxBays");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("APDL.API.Domain.VesselTypes.ValueObjects.Dimension", "MaxRows", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("MaxRows");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.OwnsOne("APDL.API.Domain.VesselTypes.ValueObjects.Dimension", "MaxTiers", b1 =>
                        {
                            b1.Property<string>("VesselTypeId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("MaxTiers");

                            b1.HasKey("VesselTypeId");

                            b1.ToTable("VesselTypes", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselTypeId");
                        });

                    b.Navigation("Capacity");

                    b.Navigation("Description");

                    b.Navigation("MaxBays");

                    b.Navigation("MaxRows");

                    b.Navigation("MaxTiers");

                    b.Navigation("Name");
                });

            modelBuilder.Entity("APDL.API.Domain.VesselVisitAggregate.VesselVisitNotification", b =>
                {
                    b.OwnsOne("APDL.API.Domain.NotificationAggregate.ValueObjects.ExpectedArrival", "ExpectedArrival", b1 =>
                        {
                            b1.Property<string>("VesselVisitNotificationId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("ExpectedArrival");

                            b1.HasKey("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitNotifications", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.OwnsOne("APDL.API.Domain.NotificationAggregate.ValueObjects.ExpectedDeparture", "ExpectedDeparture", b1 =>
                        {
                            b1.Property<string>("VesselVisitNotificationId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("ExpectedDeparture");

                            b1.HasKey("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitNotifications", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.OwnsOne("APDL.API.Domain.NotificationAggregate.ValueObjects.NotificationStatus", "Status", b1 =>
                        {
                            b1.Property<string>("VesselVisitNotificationId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Status");

                            b1.HasKey("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitNotifications", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.OwnsMany("APDL.API.Domain.NotificationAggregate.ValueObjects.SafetyOfficer", "_safetyCrewOfficers", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("OfficerName");

                            b1.Property<string>("VesselVisitNotificationId")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("Id");

                            b1.HasIndex("VesselVisitNotificationId");

                            b1.ToTable("VesselVisitSafetyOfficers", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselVisitNotificationId");
                        });

                    b.Navigation("ExpectedArrival");

                    b.Navigation("ExpectedDeparture");

                    b.Navigation("Status");

                    b.Navigation("_safetyCrewOfficers");
                });

            modelBuilder.Entity("APDL.API.Domain.Vessels.Vessel", b =>
                {
                    b.HasOne("APDL.API.Domain.VesselTypes.VesselType", "VesselType")
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("APDL.API.Domain.Vessels.ValueObjects.ImoNumber", "ImoNumber", b1 =>
                        {
                            b1.Property<Guid>("VesselId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("nvarchar(7)")
                                .HasColumnName("ImoNumber");

                            b1.HasKey("VesselId");

                            b1.ToTable("Vessels", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselId");
                        });

                    b.OwnsOne("APDL.API.Domain.Vessels.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("VesselId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("VesselId");

                            b1.ToTable("Vessels", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselId");
                        });

                    b.OwnsOne("APDL.API.Domain.Vessels.ValueObjects.Operator", "Operator", b1 =>
                        {
                            b1.Property<Guid>("VesselId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Operator");

                            b1.HasKey("VesselId");

                            b1.ToTable("Vessels", "port");

                            b1.WithOwner()
                                .HasForeignKey("VesselId");
                        });

                    b.Navigation("ImoNumber");

                    b.Navigation("Name");

                    b.Navigation("Operator");

                    b.Navigation("VesselType");
                });

            modelBuilder.Entity("APDL.API.Domain.ShippingAgentAggregate.ShippingAgent", b =>
                {
                    b.Navigation("Representatives");
                });
#pragma warning restore 612, 618
        }
    }
}
