@startuml Domain Model

package "User"{

        Entity User <<Aggregate Root>>{
        - username: String
        - password: String
        - role: String
        - email: String
        
        }

        Class UserId <<Value Object>> {
            - id: EntityId
        }

   User "1" *-- "1" UserId
}



package "Port Authority Aggregate"{

        Entity PortAuthorityOfficer <<Aggregate Root>>{
         -
        
        }

        Class PortAuthorityOfficerId <<Value Object>> {
            - id: EntityId
        }

  
 PortAuthorityOfficer "1" *-r- "1" PortAuthorityOfficerId
 PortAuthorityOfficer "0..1" --> "0..1" UserId
}

package "Shipping Agent Aggregate"{

        Entity ShippingAgentRepresentative <<Aggregate Root>>{
         
        
        }

        Class ShippingAgentRepresentativeId <<Value Object>> {
            - id: EntityId
        }

   ShippingAgentRepresentative "1" *-r- "1" ShippingAgentRepresentativeId
   ShippingAgentRepresentative "0..1" --> "0..1" UserId
}

package "Logistics Operator Aggregate"{

        Entity LogisticsOperator <<Aggregate Root>>{
         
        
        }

        Class LogisticsOperatorId <<Value Object>> {
            - id: EntityId
        }

   LogisticsOperator "1" *-r- "1" LogisticsOperatorId
   LogisticsOperator "0..1" --> "0..1" UserId
}


package "Administrator"{

        Entity Administrator <<Aggregate Root>>{
         
        
        }

        Class AdministratorId <<Value Object>> {
            - id: EntityId
        }

   Administrator "1" *-- "1" AdministratorId
   Administrator "0..1" --> "0..1" UserId
}


package "Staff"{

        Entity Staff <<Aggregate Root>>{
        - firstName: String
        - lastName: String
        - fullName: String
        - email : String
        - phoneNumber: String
        
        }

        Class StaffId <<Value Object>> {
            - id: EntityId
        }

   Staff "1" *-- "1" StaffId
   Staff "0..1" *-right- "0..1" UserId
}




package "VesselVisitNotification" {
    class VesselVisitNotification
}

package "Manifest" {
    class Manifest
}

VesselVisitNotification "1" --> "0..2" Manifest : contains

package "Vessel" {
    class Vessel
}

package "VesselTypes" {
    class VesselType
}

VesselType "1" --> "1..*" Vessel

package "Operation Type Aggregate" {

    Entity "OperationType" <<Aggregate Root>> {
            name: String

    }
    
    Class "OperationTypeId" <<ValueObject>>{
            id: EntityId
    
    }
    
    OperationType "1" *-- "1" OperationTypeId
}

package "Operation Request Aggregate" {

    Entity "OperationRequest" <<Aggregate Root>> {
            name: String

    }
    
    Class "OperationRequestId" <<ValueObject>>{
            id: EntityId
    
    }
    
    OperationRequest "1" *-- "1" OperationTypeId
}









@enduml
